frontend/art_blog/urls.py
from django.urls import path
from .views import MainPageView, DataListView, DataDetailsView, CommentView


app_name = "art_blog"
urlpatterns = [
    path("", MainPageView.as_view(), name="main_page"),  # Main Page URL
    path("data/", DataListView.as_view(), name="data_list"),  # Data List Page URL
    path(
        "data/<int:pk>/", DataDetailsView.as_view(), name="data_details"
    ),  # Data Details Page URL
    path("comment/", CommentView.as_view(), name="comment_box"),  # Comment Box URL
]

frontend/art_shop/urls.py
from django.contrib import admin
from django.shortcuts import HttpResponse
from django.urls import path
from .views import CreateArtistView, CreateUserView, add_artwork
from django.views.generic import TemplateView
from . import views

app_name = "art_shop"
urlpatterns = [
    path('buy/<int:pk>', lambda request: HttpResponse("<p>Not implemented yet</p>"), name='buyproduct'),
    path('bought/<int:pk>', TemplateView.as_view(template_name="success.html"), name='success'),
    path("register/artist/", CreateArtistView.as_view(), name="register_artist"),
    path("register/user/", CreateUserView.as_view(), name="register_user"),
    path("upload/", add_artwork, name="upload"),
    path("uploaded/", TemplateView.as_view(template_name="artwork_uploaded.html"), name="upload_success"),
]

frontend/djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("art_blog/", include("art_blog.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path(
        "logout/", auth_views.LogoutView.as_view(next_page="/art_blog/"), name="logout"
    ),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="registration/login.html", success_url="/art_blog/data_list/"
        ),
        name="login",
    ),
    path("", RedirectView.as_view(url="/art_blog/")),
    path("art_shop/", include("art_shop.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/art_blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Comment(models.Model):
    user_fname = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=500)
    time = models.DateTimeField(auto_now=True)
    item = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.user_fname}: '{self.message}'"

class Vote(models.Model):
    item = models.PositiveIntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

frontend/art_blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["message"]

frontend/art_blog/views.py
from typing import Any
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, ListView, DetailView
from .forms import CommentForm
from .models import Comment, Vote
from art_shop.models import Selledartwork, ArtworkToSell
from django.conf import settings
import requests
import json


class MainPageView(TemplateView):
    template_name = "main_page.html"


class DataListView(TemplateView):
    template_name = "data_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        artwork_list_url = settings.ART_API_URL+"artwork/"
        response = requests.get(artwork_list_url)
        list_json = response.json()
        context["items"] = list_json
        return context


class DataDetailsView(TemplateView):
    template_name = "data_details.html"
    context_object_name = "item"

    def post(self, request, *args, **kwargs):
        # Handling comment submission
        form = CommentForm(request.POST)
        pk = kwargs["pk"]
        print("PK:", pk)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user_fname = request.user
            comment.item = pk
            comment.save()
            return redirect(self.request.path_info)

        # Handling voting action
        if 'vote' in request.POST:
            if self.request.user.pk in Vote.objects.filter(item=pk).values_list("user", flat=True):
                existing_vote = Vote.objects.filter(item=pk, user=self.request.user.pk).first()
                if existing_vote:
                    existing_vote.delete()
            else:
                Vote.objects.create(item=pk, user=self.request.user)
            return redirect(self.request.path_info)

        return super().post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = kwargs["pk"]
        artwork_list_url = settings.ART_API_URL+"artwork/"+str(pk)
        response = requests.get(artwork_list_url)
        item = response.json()
        context["item"] = item
        is_sold = Selledartwork.objects.filter(item=pk).exists()
        if is_sold:
            context["price"] = Selledartwork.objects.filter(item=pk).values_list("price", flat=True).first()
        else:
            context["price"] = ArtworkToSell.objects.filter(item=pk).values_list("price", flat=True).first()
        context["is_sold"] = is_sold
        context["voters"] = Vote.objects.filter(item=pk)
        vote_users = Vote.objects.filter(item=pk).values_list("user", flat=True)
        context["did_vote"] = self.request.user.pk in vote_users
        context["comments"] = Comment.objects.filter(item=pk)
        context["comment_form"] = CommentForm()
        return context


class CommentView(TemplateView):
    # template_name = "comment_box.html"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["form"] = CommentForm()
    #     return context

    # def post(self, request, *args, **kwargs):
    #     form = CommentForm(request.POST)
    #     if form.is_valid():
    #         comment = form.save()  # Save the comment to the database
    #         return redirect("comment_success")  # Redirect to a success page
    #     else:
    #         return render(request, self.template_name, {"form": form})
    pass

frontend/art_blog/templates/comment_box.html
<!DOCTYPE html>
<head>
    <title>Comment Box</title>
</head>
<body>
    <h1>Leave a Comment</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

frontend/art_blog/templates/comment_success.html
<!DOCTYPE html>
<head>
 
    <title>Comment Success</title>
</head>
<body>
    <h1>Your comment has been submitted successfully!</h1>
    
</body>
</html>

frontend/art_blog/templates/data_details.html
{% extends "main.html" %}
{% block title %}
    <h1>'{{item.name}}'</h1>
    <h3>by {{item.artist}}</h3>
{% endblock title %}
{% block content %}
    <div style="display: flex; justify-content: space-evenly; align-items: center;">
        <div>
            <h3>Details for '{{item.name}}'</h3>
            <h4>Artist: {{ item.artist }}</h4>
            <p>size: {{ item.size.width }}cm * {{ item.size.height }}cm</p>
            <p>price: {{price}} €</p>
        </div>
        <div style="display: flex;">
            {% if user.is_authenticated %}
                <button class="btn btn-outline-primary" style="margin: 20px;" type="submit" form="voteForm">
                    {% if did_vote %}
                        unVote
                    {% else %}
                        Vote
                    {% endif %}
                </button>
                <form id="voteForm" method="post" style="display: none;">
                    {% csrf_token %}
                    <input type="hidden" name="vote" value="1">
                </form>
            {% endif %}
            {% with voters=voters.all %}
                <ul>
                    <li style="list-style: none;">Voters: {{voters|length}}</li>
                    {% for voter in voters %}
                        <li>{{voter.user.username}}</li>
                    {% endfor %}
                </ul>
            {% endwith %}
        </div>
        {% if user.is_authenticated %}
            {% if not is_sold %}
                <a href="{% url 'art_shop:buyproduct' item.pk %}" class="btn btn-outline-success" style="margin: 20px;">buy now</a>
            {% else %}
                <p>Item already sold.</p>
            {% endif %}
        {% endif %}
    </div>
        {% with item.image as image_path %}
            {% if image_path %}
                <img src="{{ image_path }}" alt="{{ item.name }}" style="margin: 100px; max-height:700px;">
            {% endif %}
        {% endwith %}
    <div style="float: right; margin-top:300px;">
        {%if comments %}
        <h4 style="text-align: end;">user comments:</h4>
        {% endif %}
        {% for comment in  comments %}
            <p style="text-align: end;">{{comment}}</p>
        {% endfor %}
        {% if user.is_authenticated %}
        <h4 style="text-align: end; margin-top: 50px;">Your comment:</h4>
        <form method="post">
            {% csrf_token %}
            {{ comment_form }}
            <input  class="btn btn-outline-primary" type="submit" value="post comment">
        </form>
        {% endif %}
    </div>
{% endblock content %}

frontend/art_blog/templates/data_list.html
{% extends "main.html" %}
{% block title %}<h1>Our ArtWorks</h1>{% endblock title %}
{% block content %}
    <h1 style="text-align: end;">Our Artworks List:</h1>
    <ul style="margin: 100px;">
        {% for item in items %}
            <li style="width: 300px; display: flex; justify-content: space-between; margin: 20px; align-items: center;">
                <a href="{% url 'art_blog:data_details' item.pk %}">{{ item.name }} ({{ item.artist }})</a>
                {% with item.image as image_path %}
                    {% if image_path %}
                        <img src="{{ image_path }}" alt="{{ item.name }}" style="max-height: 80px;">
                    {% endif %}
                {% endwith %}
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

frontend/art_blog/templates/main_page.html
{% extends "main.html" %}
{% block title %}<h1>Welcome to the Main Page of our ArtBlog</h1>{% endblock title %}