frontend/art_blog/urls.py
from django.urls import path
from .views import MainPageView, DataListView, DataDetailsView, CommentView


app_name = "art_blog"
urlpatterns = [
    path("", MainPageView.as_view(), name="main_page"),  # Main Page URL
    path("data/", DataListView.as_view(), name="data_list"),  # Data List Page URL
    path(
        "data/<int:pk>/", DataDetailsView.as_view(), name="data_details"
    ),  # Data Details Page URL
    path("comment/", CommentView.as_view(), name="comment_box"),  # Comment Box URL
]

frontend/art_shop/urls.py
from django.contrib import admin
from django.shortcuts import HttpResponse
from django.urls import path
from .views import CreateArtistView, CreateUserView, add_artwork
from django.views.generic import TemplateView
from . import views

app_name = "art_shop"
urlpatterns = [
    path('buy/<int:pk>', lambda request: HttpResponse("<p>Not implemented yet</p>"), name='buyproduct'),
    path('bought/<int:pk>', TemplateView.as_view(template_name="success.html"), name='success'),
    path("register/artist/", CreateArtistView.as_view(), name="register_artist"),
    path("register/user/", CreateUserView.as_view(), name="register_user"),
    path("upload/", add_artwork, name="upload"),
    path("uploaded/", TemplateView.as_view(template_name="artwork_uploaded.html"), name="upload_success"),
]

frontend/djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("art_blog/", include("art_blog.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path(
        "logout/", auth_views.LogoutView.as_view(next_page="/art_blog/"), name="logout"
    ),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="registration/login.html", success_url="/art_blog/data_list/"
        ),
        name="login",
    ),
    path("", RedirectView.as_view(url="/art_blog/")),
    path("art_shop/", include("art_shop.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ART</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        /* Set background color */
        body {
            align-items: end;
            background-color: #e9ecef; /* light grey background color */
            text-shadow: -2px 2px 7px rgba(0, 132, 255, 0.2);
        }

        /* Move buttons to left side */
        .btn-left {
            text-align: left;
        }

        ul li {
        margin-bottom: 10px; /* Adjust the margin to whatever spacing you prefer */
        }
        img, button, input {
            box-shadow: -10px 10px 25px rgba(0, 132, 255, 0.1);
        }
    </style>
</head>
<header style="text-align: center;">{% block title %}{% endblock title %}</header>
<body style="margin: 50px;">
    <div style="display: flex;">
        <nav style="width: 270px;">
            <ul style="list-style: none; margin-top: 100px;">
                {% if user.is_authenticated %}
                    <li>you're logged in as <span style="font-style: italic;">{{ user.username }}</span></li>
                    <li><form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-outline-primary" type="submit">Logout</button>
                    </form></li>
                    {% if user.is_staff %}
                        <li><a class="btn btn-outline-success" href="{% url 'art_shop:upload' %}">upload Artwork</a></li>
                    {% endif %}
                {% else %}
                    <li><a href="{% url 'login' %}" class="btn btn-outline-primary">log in</a></li>
                    <li><a class="btn btn-outline-success" href="{% url 'art_shop:register_user' %}">register as user</a></li>
                {% endif %}
                <li><a href="{% url 'art_blog:main_page' %}">Home page</a></li>
                <li><a href="{% url 'art_blog:data_list' %}">Our ArtWorks</a></li>
            </ul>
        </nav>
        <section>
            {% block content %}{% endblock %}
        </section>
    </div>
</body>
</html>



    